### ISSUE TITLE
AS50 muzzleflash missing textures

### ISSUE THREAD

**Issue by ghost** [HaodongMo/tacrp#1]
happens for both workshop and github versions of the weps

`C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "muzzleflash_M82"!`
![image](https://user-images.githubusercontent.com/27306442/203188003-a70d8a28-138a-4e35-8705-40eb97b442a7.png)

**Comment by TheOnly8Z** [comment]
Fixed some time ago.
