### ISSUE TITLE
Messed up wrists on multiple weapons across different packs

### ISSUE THREAD

**Issue by BadaBingBR** [HaodongMo/tacrp#15]
![gmod 2024-01-05 23-00-20](https://github.com/HaodongMo/tacrp/assets/83316350/54b5db05-f1d9-49f1-b3c1-0205fc211177)
![gmod 2024-01-05 23-00-28](https://github.com/HaodongMo/tacrp/assets/83316350/d2563b2a-a284-463d-a10a-d89d47cce950)
![gmod 2024-01-05 23-01-49](https://github.com/HaodongMo/tacrp/assets/83316350/2f6f2355-302c-4c93-8f41-2f91172b05cb)

Some weapons work well with c_hands and other don't, this happens on multiple packs (Interops, AR, SD, IC, HO)

(The SIG 550 Sniper seem to have messed up wrists no matter the c_hands)

**Comment by Jayrazer** [comment]
We are working to remedy this but you should know that between TacInt's weird rig and default Garry's Mod playermodels having awful c_hands that things like this are bound to happen.
